name: CI Debug
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Debug Environment
          run: |
            pwd
            ls -la
            node --version
            npm --version
        - name: Install
          run: |
            npm install
            npm list wdio
        - name: Debug After Install
          run: |
            ls -la
            ls -la node_modules/.bin
            which wdio
            ls -l $(which wdio)
        - name: Test 
          env: 
            BROWSERSTACK_USERNAME: ${{ secrets.BS_USER }}
            BROWSERSTACK_ACCESS_KEY: ${{ secrets.BS_KEY }}
          run: |
            echo "Running WebdriverIO test..."
            npx wdio --version
            npx wdio --spec ./test/specs/contact-us.js
        - uses: actions/upload-artifact@v3
          if: always()
          with:
            name: logs
            path: logs