name: CI Debug
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Debug Environment
          run: |
            pwd
            ls -la
            node --version
            npm --version
        - name: Install
          run: |
            npm install
        - name: Test 
          env: 
            BROWSERSTACK_USERNAME: ${{ secrets.BS_USER }}
            BROWSERSTACK_ACCESS_KEY: ${{ secrets.BS_KEY }}
          run: |
            echo "Running WebdriverIO test..."
            npx wdio --version
            cat wdio.conf.js
            DEBUG=true npx wdio --spec ./test/specs/contact-us.js
        - name: Debug on Failure
          if: failure()
          run: |
            echo "Test failed. Debugging..."
            cat ./logs/wdio.log
        - uses: actions/upload-artifact@v3
          if: always()
          with:
            name: logs
            path: logs