name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install
          run: npm install
        - name: Test 
          env: 
            # BROWSERSTACK_USERNAME: ${{secrets.BS_USER}}
            # BROWSERSTACK_ACCESS_KEY: ${{secrets.BS_KEY}}
            user: 'ahmadfadliehadib_AzGhEB',
            key: '6FzybP8va7qjbxxNV68m',
          run: npx wdio wdio.conf.js --spec test/specs/contact-us.js
        - uses: actions/upload-artifact@v3
          if: failure()
          with:
            name: logs
            path: logs
